language: python

python:
  - '3.6'

install:
  - pip install -r requirements.txt


services:
 - postgresql

before_script:
 - psql -c 'CREATE DATABASE diary;' -U postgres

script:
- pytest

after_success:
 - coveralls


