language: python

python:
  - '3.4'

install:
  - pip install -r requirements.txt


services:
 - postgresql

before_script:
 - psql -c 'CREATE DATABASE diary;' -U postgres

script:
- pytest tests

after_success:
 - coveralls


